import { useEffect, useState } from "react";
import { api } from "./lib/api";

type Server={id:string;name:string;status:string;memory:number;disk:number;cpu:number;version?:string;node?:{id:string;name:string;status:string};allocation?:{ip:string;port:number}};
type Node={id:string;name:string;host?:string;port?:number;status:string};

export default function App(){
 const [servers,setServers]=useState<Server[]>([]),[nodes,setNodes]=useState<Node[]>([]),[apiStatus,setApiStatus]=useState("Checking..."),[error,setError]=useState(""),[showCreate,setShowCreate]=useState(false),[showNode,setShowNode]=useState(false),[busy,setBusy]=useState(false);
 const [form,setForm]=useState({name:"",nodeId:"",memory:"2048",disk:"10",cpu:"100",version:"LATEST"});
 const [nodeForm,setNodeForm]=useState({name:"",host:"",port:"8080",token:""});
 async function load(){setError("");try{await api("/api/health");setApiStatus("Online");const [s,n]=await Promise.all([api("/api/servers"),api("/api/nodes")]);setServers(s.servers??[]);setNodes(n.nodes??[]);setForm(x=>({...x,nodeId:x.nodeId||n.nodes?.[0]?.id||""}));}catch(e){setApiStatus("Offline");setError(e instanceof Error?e.message:"Unable to connect to API")}}
 useEffect(()=>{void load()},[]);
 async function addNode(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{await api("/api/nodes",{method:"POST",body:JSON.stringify({name:nodeForm.name,host:nodeForm.host,port:Number(nodeForm.port),token:nodeForm.token})});setShowNode(false);setNodeForm({name:"",host:"",port:"8080",token:""});await load()}catch(e){setError(e instanceof Error?e.message:"Node creation failed")}finally{setBusy(false)}}
 async function pingNode(id:string){setBusy(true);setError("");try{await api(`/api/nodes/${id}/ping`,{method:"POST"});await load()}catch(e){setError(e instanceof Error?e.message:"Node ping failed")}finally{setBusy(false)}}
 async function createServer(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const d=await api("/api/servers",{method:"POST",body:JSON.stringify({...form,memory:Number(form.memory),disk:Number(form.disk),cpu:Number(form.cpu)})});setServers(x=>[d.server,...x]);setShowCreate(false);setForm(x=>({...x,name:""}))}catch(e){setError(e instanceof Error?e.message:"Server creation failed")}finally{setBusy(false)}}
 async function action(id:string,a:string){setBusy(true);setError("");try{await api(`/api/servers/${id}/${a}`,{method:"POST"});await load()}catch(e){setError(e instanceof Error?e.message:`${a} failed`)}finally{setBusy(false)}}
 return <div className="app">
  <aside className="sidebar"><div className="brand">BilloreCloud</div><nav><button className="active">Dashboard</button><button>Servers</button><button onClick={()=>setShowNode(true)}>Nodes</button><button>Billing</button><button>Support</button></nav></aside>
  <main className="main"><header className="topbar"><div><p className="eyebrow">CONTROL PANEL</p><h1>Dashboard</h1></div><div className="top-actions"><span className="badge">API: {apiStatus}</span><button onClick={()=>void load()}>Refresh</button></div></header>
   {error&&<div className="alert">{error}</div>}
   <section className="cards"><div className="card"><span>Servers</span><strong>{servers.length}</strong></div><div className="card"><span>Online</span><strong>{servers.filter(s=>s.status==="ONLINE").length}</strong></div><div className="card"><span>Nodes</span><strong>{nodes.length}</strong></div><div className="card"><span>Online Nodes</span><strong>{nodes.filter(n=>n.status==="online").length}</strong></div></section>
   <section className="panel"><div className="panel-title"><h2>Nodes</h2><button onClick={()=>setShowNode(true)}>Add Node</button></div>{nodes.length===0?<div className="empty"><strong>No nodes registered</strong><p>Add your VPS as a node first.</p></div>:<div className="server-list">{nodes.map(n=><div className="server" key={n.id}><div><h3>{n.name}</h3><p>{n.host}:{n.port}</p></div><div className="top-actions"><span className={`status ${n.status}`}>{n.status}</span><button disabled={busy} onClick={()=>void pingNode(n.id)}>Ping</button></div></div>)}</div>}</section>
   <section className="panel"><div className="panel-title"><h2>My Servers</h2><button onClick={()=>setShowCreate(true)} disabled={!nodes.length}>Create Server</button></div>{!nodes.length&&<div className="notice">Add an online node before creating a Minecraft server.</div>}{servers.length===0?<div className="empty"><strong>No servers yet</strong><p>Create a Minecraft server after adding a node.</p></div>:<div className="server-list">{servers.map(s=><div className="server" key={s.id}><div><h3>{s.name}</h3><p>{s.memory} MB RAM · {s.disk} GB Disk · {s.cpu}% CPU · {s.version??"LATEST"}</p><small>{s.node?.name??"No node"}{s.allocation?` · ${s.allocation.ip}:${s.allocation.port}`:""}</small></div><div className="top-actions"><span className={`status ${s.status.toLowerCase()}`}>{s.status}</span>{s.status!=="ONLINE"&&<button disabled={busy} onClick={()=>void action(s.id,"start")}>Start</button>}{s.status==="ONLINE"&&<button disabled={busy} onClick={()=>void action(s.id,"stop")}>Stop</button>}<button disabled={busy} onClick={()=>void action(s.id,"restart")}>Restart</button></div></div>))}</div>}</section>
  </main>
  {showCreate&&<div className="modal-backdrop"><form className="modal" onSubmit={createServer}><div className="modal-head"><h2>Create Minecraft Server</h2><button type="button" className="close" onClick={()=>setShowCreate(false)}>×</button></div><label>Server Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Survival SMP"/></label><label>Node<select required value={form.nodeId} onChange={e=>setForm({...form,nodeId:e.target.value})}>{nodes.map(n=><option key={n.id} value={n.id}>{n.name} ({n.status})</option>)}</select></label><label>Minecraft Version<input value={form.version} onChange={e=>setForm({...form,version:e.target.value})} placeholder="LATEST or 1.21.8"/></label><div className="form-grid"><label>RAM MB<input type="number" min="512" value={form.memory} onChange={e=>setForm({...form,memory:e.target.value})}/></label><label>Disk GB<input type="number" min="1" value={form.disk} onChange={e=>setForm({...form,disk:e.target.value})}/></label><label>CPU %<input type="number" min="1" value={form.cpu} onChange={e=>setForm({...form,cpu:e.target.value})}/></label></div><p className="modal-note">The node agent creates an isolated Paper Minecraft container with a persistent data directory.</p><button className="create-button" disabled={busy||!form.nodeId}>{busy?"Creating...":"Create Server"}</button></form></div>}
  {showNode&&<div className="modal-backdrop"><form className="modal" onSubmit={addNode}><div className="modal-head"><h2>Add Node</h2><button type="button" className="close" onClick={()=>setShowNode(false)}>×</button></div><label>Node Name<input required value={nodeForm.name} onChange={e=>setNodeForm({...nodeForm,name:e.target.value})} placeholder="VPS Node 1"/></label><label>Agent Host/IP<input required value={nodeForm.host} onChange={e=>setNodeForm({...nodeForm,host:e.target.value})} placeholder="203.0.113.10"/></label><label>Agent Port<input type="number" min="1" max="65535" required value={nodeForm.port} onChange={e=>setNodeForm({...nodeForm,port:e.target.value})}/></label><label>Agent Token<input required type="password" value={nodeForm.token} onChange={e=>setNodeForm({...nodeForm,token:e.target.value})} placeholder="Same as AGENT_TOKEN"/></label><p className="modal-note">Run the agent on the Minecraft VPS and use its AGENT_TOKEN here.</p><button className="create-button" disabled={busy}>{busy?"Adding...":"Add Node"}</button></form></div>}
 </div>
}
